/**
 * Bill Model (PostgreSQL)
 * Main billing table with ACID transaction support
 */

const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
    const Bill = sequelize.define('Bill', {
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
        },
        bill_number: {
            type: DataTypes.STRING(20),
            unique: true,
            allowNull: false,
        },
        // MongoDB references stored as strings
        patient_id: {
            type: DataTypes.STRING(30),
            allowNull: false,
            comment: 'MongoDB Patient ObjectId',
        },
        visit_id: {
            type: DataTypes.STRING(30),
            allowNull: true,
            comment: 'MongoDB Visit ObjectId (Appointment/Admission/Emergency)',
        },
        visit_model: {
            type: DataTypes.ENUM('Appointment', 'Admission', 'Emergency'),
            allowNull: true,
        },
        visit_type: {
            type: DataTypes.STRING(10),
            defaultValue: 'opd',
        },
        bill_date: {
            type: DataTypes.DATE,
            defaultValue: DataTypes.NOW,
        },
        status: {
            type: DataTypes.ENUM('draft', 'finalized', 'cancelled'),
            defaultValue: 'draft',
        },
        subtotal: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        total_discount: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        total_tax: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        grand_total: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        paid_amount: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        balance_amount: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        payment_status: {
            type: DataTypes.ENUM('pending', 'partial', 'paid', 'refunded'),
            defaultValue: 'pending',
        },
        // Insurance
        insurance_claim_id: {
            type: DataTypes.STRING(30),
            allowNull: true,
            comment: 'MongoDB Insurance ObjectId',
        },
        insurance_status: {
            type: DataTypes.ENUM('none', 'pending', 'submitted', 'approved', 'rejected', 'settled'),
            defaultValue: 'none',
        },
        patient_responsibility: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        insurance_responsibility: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        // Discount workflow
        discount_request_amount: {
            type: DataTypes.DECIMAL(12, 2),
            defaultValue: 0,
        },
        discount_request_reason: {
            type: DataTypes.TEXT,
            allowNull: true,
        },
        discount_requested_by: {
            type: DataTypes.STRING(30),
            allowNull: true,
        },
        discount_requested_at: {
            type: DataTypes.DATE,
            allowNull: true,
        },
        discount_status: {
            type: DataTypes.ENUM('none', 'pending', 'approved', 'rejected'),
            defaultValue: 'none',
        },
        discount_approved_by: {
            type: DataTypes.STRING(30),
            allowNull: true,
        },
        discount_approval_date: {
            type: DataTypes.DATE,
            allowNull: true,
        },
        discount_rejection_reason: {
            type: DataTypes.TEXT,
            allowNull: true,
        },
        // Lock mechanism
        is_locked: {
            type: DataTypes.BOOLEAN,
            defaultValue: false,
        },
        locked_at: {
            type: DataTypes.DATE,
            allowNull: true,
        },
        locked_by: {
            type: DataTypes.STRING(30),
            allowNull: true,
        },
        // Generated by
        generated_by: {
            type: DataTypes.STRING(30),
            allowNull: false,
            comment: 'MongoDB User ObjectId',
        },
        // MongoDB reference for backward compatibility
        mongo_id: {
            type: DataTypes.STRING(30),
            allowNull: true,
            comment: 'Original MongoDB ObjectId (for migration)',
        },
    }, {
        tableName: 'bills',
        timestamps: true,
        underscored: true,
        indexes: [
            { fields: ['patient_id'] },
            { fields: ['bill_date'] },
            { fields: ['payment_status'] },
            { fields: ['status'] },
            { fields: ['mongo_id'] },
        ],
        hooks: {
            beforeCreate: async (bill) => {
                // Auto-generate bill number
                if (!bill.bill_number) {
                    const today = new Date();
                    const dateStr = today.toISOString().slice(0, 10).replace(/-/g, '');
                    const count = await Bill.count();
                    bill.bill_number = `BILL${dateStr}${String(count + 1).padStart(5, '0')}`;
                }
            },
            beforeSave: (bill) => {
                // Calculate balance
                bill.balance_amount = parseFloat(bill.grand_total) - parseFloat(bill.paid_amount);
                
                // Update payment status
                const paid = parseFloat(bill.paid_amount);
                const total = parseFloat(bill.grand_total);
                
                if (paid >= total && total > 0) {
                    bill.payment_status = 'paid';
                } else if (paid > 0) {
                    bill.payment_status = 'partial';
                } else {
                    bill.payment_status = 'pending';
                }
            },
        },
    });

    /**
     * Recalculate totals from items
     */
    Bill.prototype.recalculateTotals = async function(transaction = null) {
        const BillItem = sequelize.models.BillItem;
        
        const items = await BillItem.findAll({
            where: { bill_id: this.id },
            transaction,
        });

        this.subtotal = items.reduce((sum, item) => sum + parseFloat(item.amount), 0);
        this.total_discount = items.reduce((sum, item) => sum + parseFloat(item.discount || 0), 0);
        this.total_tax = items.reduce((sum, item) => sum + parseFloat(item.tax || 0), 0);
        this.grand_total = this.subtotal - this.total_discount + this.total_tax;
        this.balance_amount = this.grand_total - parseFloat(this.paid_amount);

        await this.save({ transaction });
    };

    return Bill;
};
